namespace Sandbox103.V2;

/// <summary>
/// Represents a log drop for a particular repository generated by a
/// remote build which produces MSBuild <c>.binlog</c> files.
/// </summary>
public sealed class LogDrop : ILogDrop
{
    private readonly string _path;
    private readonly IReadOnlyCollection<IBinaryLog> _binaryLogs;

    public LogDrop(string path, IReadOnlyCollection<IBinaryLog> binaryLogs)
    {
        ThrowHelper.ThrowIfDirectoryNotFound(path);
        ArgumentNullException.ThrowIfNull(binaryLogs);

        _path = path;
        _binaryLogs = binaryLogs;
    }

    /// <inheritdoc/>
    public string Path => _path;

    /// <inheritdoc/>
    public IReadOnlyCollection<IBinaryLog> BinaryLogs => _binaryLogs;
}
