namespace Sandbox103.V2.Abstractions;

/// <summary>
/// Reads <c>.binlog</c> files generated by MSBuild.
/// </summary>
public interface IBinaryLogReader
{
    /// <summary>
    /// Read a <c>.binlog</c> file generated by MSBuild.
    /// </summary>
    /// <param name="options">The options for reading this binary log file.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>Representation of a binary log generated by MSBuild.</returns>
    public Task<IBinaryLog> ReadAsync(BinaryLogReaderOptions options, CancellationToken cancellationToken);
}
